common: &common
  - 'harpy/common/**'
  - 'harpy/__main__.py'
  - 'harpy/validation/**'
  - 'harpy/report/*.py'
  - '.github/workflows/tests.yml'
  - '.github/filters.yml'
  - 'pyproject.toml'
environments: &environments
  - 'harpy/common/environments.py'
  - 'harpy/commands/environments.py'
  - 'harpy/snakefiles/environments.smk'
validate: &validate
  - *common
  - *environments
  - 'harpy/commands/validate.py'
  - 'harpy/snakefiles/validate_fastq.smk'
  - 'harpy/snakefiles/validate_bam.smk'
  - 'test/fastq/**'
  - 'test/bam/**'
  - 'harpy/utils/check_bam.py'
  - 'harpy/utils/check_fastq.py'
  - 'harpy/notebooks/validate_fastq.ipynb'
  - 'harpy/notebooks/validate_bam.ipynb'
deconvolve: &deconvolve
  - *common
  - *environments
  - 'harpy/commands/deconvolve.py'
  - 'harpy/snakefiles/deconvolve.smk'
  - 'harpy/validation/fastq.py'
preproc: &preproc
  - *common
  - *environments
  - 'haplotag-acbd.py'
  - 'harpy/commands/preprocess.py'
  - 'harpy/snakefiles/preprocess**.smk'
  - 'harpy/validation/fastq.py'
  - 'test/data/preproc/**'
qc: &qc
  - *common
  - *environments
  - 'harpy/commands/qc.py'
  - 'harpy/snakefiles/qc.smk'
  - 'harpy/utils/bx_stats_fq.py'
  - 'harpy/validation/fastq.py'
  - 'test/fastq/**'
  - 'harpy/notebooks/fastp_qc.ipynb'
  - 'harpy/notebooks/qc_bx_stats.ipynb'
align: &align
  - *common
  - *environments
  - 'harpy/utils/standardize/standardize.go'
  - 'harpy/commands/align.py'
  - 'harpy/snakefiles/align_bwa.smk'
  - 'harpy/snakefiles/align_strobe.smk'
  - 'harpy/snakefiles/align_minimap.smk'
  - 'harpy/snakefiles/align.smk'
  - 'harpy/notebooks/align_stats.ipynb'
  - 'harpy/notebooks/align_lrstats.ipynb'
  - 'harpy/notebooks/samtools_stats.ipynb'
  - 'harpy/utils/bx_stats_sam.py'
  - 'harpy/utils/molecule_coverage.py'
  - 'harpy/validation/fasta.py'
  - 'harpy/validation/fastq.py'
  - 'test/fastq/**'
snp: &snp
  - *common
  - *environments
  - 'harpy/commands/snp.py'
  - 'harpy/snakefiles/snp_mpileup.smk'
  - 'harpy/snakefiles/snp_freebayes.smk'
  - 'harpy/notebooks/bcftools_stats.ipynb'
  - 'harpy/validation/fasta.py'
  - 'harpy/validation/xam.py'
  - 'test/bam/**'
impute: &impute
  - *common
  - *environments
  - 'harpy/commands/impute.py'
  - 'harpy/snakefiles/impute.smk'
  - 'harpy/notebooks/impute.ipynb'
  - 'harpy/notebooks/stitch_collate.ipynb'
  - 'harpy/validation/fasta.py'
  - 'harpy/validation/xam.py'
  - 'test/bam/**'
  - 'test/vcf/test.bcf'
leviathan: &leviathan
  - *common
  - *environments
  - 'harpy/commands/sv.py'
  - 'harpy/snakefiles/sv_leviathan.smk'
  - 'harpy/notebooks/sv.ipynb'
  - 'harpy/validation/fasta.py'
  - 'harpy/validation/xam.py'
  - 'test/bam/**'
naibr: &naibr
  - *common
  - *environments
  - 'harpy/commands/sv.py'
  - 'harpy/snakefiles/sv_naibr.smk'
  - 'harpy/notebooks/sv.ipynb'
  - 'harpy/utils/infer_sv.py'
  - 'harpy/validation/fasta.py'
  - 'harpy/validation/xam.py'
  - 'test/bam_phased/**'
phase: &phase
  - *common
  - *environments
  - 'harpy/commands/phase.py'
  - 'harpy/snakefiles/phase_snp.smk'
  - 'harpy/snakefiles/phase_bam.smk'
  - 'harpy/validation/fasta.py'
  - 'harpy/validation/xam.py'
  - 'test/bam/**'
  - 'test/vcf/test.bcf'
  - 'test/vcf/test.phased.bcf'
  - 'harpy/notebooks/hapcut.ipynb'
  - 'harpy/utils/parse_phaseblocks.py'
assembly: &assembly
  - *common
  - *environments
  - 'harpy/commands/assembly.py'
  - 'harpy/commands/metassembly.py'
  - 'harpy/snakefiles/assembly.smk'
  - 'harpy/snakefiles/metassembly.smk'
  - 'harpy/validation/fasta.py'
  - 'harpy/validation/fastq.py'
other: &other
  - *common
  - 'harpy/commands/template.py'
  - 'harpy/commands/hpc.py'
resume: &resume
  - 'harpy/commands/resume.py'
