common: &common
  - 'harpy/_launch.py'
  - 'harpy/_misc.py'
  - 'harpy/_cli_types_generic.py'
  - 'harpy/_cli_types_params.py'
  - 'harpy/_parsers.py'
  - 'harpy/_printing.py'
  - 'harpy/_validations.py'
  - 'harpy/__main__.py'
  - 'resources/harpy.yaml'
  - '.github/workflows/tests.yml'
  - '.github/filters.yml'
  - 'resources/buildforCI.sh'
container: &container
  - 'harpy/_conda.py'
  - 'harpy/container.py'
  - 'harpy/containerize.smk'
preflight: &preflight
  - *common
  - *container
  - 'harpy/preflight.py'
  - 'harpy/snakefiles/preflight_fastq.smk'
  - 'harpy/snakefiles/preflight_bam.smk'
  - 'test/fastq/**'
  - 'test/bam/**'
  - 'harpy/bin/check_bam.py'
  - 'harpy/bin/check_fastq.py'
  - 'harpy/reports/preflight_fastq.Rmd'
  - 'harpy/reports/preflight_bam.Rmd'
deconvolve: &deconvolve
  - *common
  - *container
  - 'harpy/deconvolve.py'
  - 'harpy/snakefiles/deconvolve.smk'
demux: &demux
  - *common
  - *container
  - 'harpy/demultiplex.py'
  - 'harpy/snakefiles/demultiplex**.smk'
  - '**demuxGen1'
  - 'haplotag_acbd.py'
  - 'test/data/demux/**'
qc: &qc
  - *common
  - *container
  - 'harpy/qc.py'
  - 'harpy/snakefiles/qc.smk'
  - 'test/fastq/**'
bwa: &bwa
  - *common
  - *container
  - 'harpy/align.py'
  - 'harpy/snakefiles/align_bwa.smk'
  - 'harpy/reports/align_stats.Rmd'
  - 'harpy/reports/align_bxstats.Rmd'
  - 'harpy/bin/bx_stats.py'
  - 'harpy/bin/count_bx.py'
  - 'harpy/bin/assign_mi.py'
  - 'harpy/bin/make_windows.py'
  - 'test/fastq/**'
ema: &ema
  - *common
  - *container
  - 'harpy/align.py'
  - 'harpy/snakefiles/align_ema.smk'
  - 'harpy/reports/align_stats.Rmd'
  - 'harpy/reports/align_bxstats.Rmd'
  - 'harpy/bin/bx_stats.py'
  - 'harpy/bin/count_bx.py'
  - 'harpy/bin/make_windows.py'
  - 'test/fastq/**'
strobealign: &strobealign
  - *common
  - *container
  - 'harpy/align.py'
  - 'harpy/snakefiles/align_strobealign.smk'
  - 'harpy/reports/align_stats.Rmd'
  - 'harpy/reports/align_bxstats.Rmd'
  - 'harpy/bin/assign_mi.py'
  - 'harpy/bin/bx_stats.py'
  - 'harpy/bin/count_bx.py'
  - 'harpy/bin/make_windows.py'
  - 'test/fastq/**'
mpileup: &mpileup
  - *common
  - *container
  - 'harpy/snp.py'
  - 'harpy/snakefiles/snp_mpileup.smk'
  - 'harpy/reports/bcftools_stats.Rmd'
  - 'harpy/bin/make_windows.py'
  - 'test/bam/**'
freebayes: &freebayes
  - *common
  - *container
  - 'harpy/snp.py'
  - 'harpy/snakefiles/snp_freebayes.smk'
  - 'harpy/reports/bcftools_stats.Rmd'
  - 'harpy/bin/make_windows.py'
  - 'test/bam/**'
impute: &impute
  - *common
  - *container
  - 'harpy/impute.py'
  - 'harpy/snakefiles/impute.smk'
  - 'test/bam/**'
  - 'test/vcf/test.bcf'
  - 'harpy/reports/impute.Rmd'
  - 'harpy/reports/stitch_collate.Rmd'
  - 'harpy/scripts/stitch_impute.R'
leviathan: &leviathan
  - *common
  - *container
  - 'harpy/sv.py'
  - 'harpy/snakefiles/sv_leviathan**.smk'
  - 'test/bam/**'
  - 'harpy/bin/concatenate_bam.py'
  - 'harpy/reports/leviathan**.Rmd'
naibr: &naibr
  - *common
  - *container
  - 'harpy/sv.py'
  - 'harpy/snakefiles/sv_naibr**.smk'
  - 'harpy/bin/concatenate_bam.py'
  - 'test/bam/**'
  - 'test/bam_phased/**'
  - 'test/vcf/test.phased.bcf'
  - 'harpy/reports/naibr**.Rmd'
  - 'harpy/bin/infer_sv.py'
phase: &phase
  - *common
  - *container
  - 'harpy/phase.py'
  - 'harpy/snakefiles/phase.smk'
  - 'test/bam/**'
  - 'test/vcf/test.bcf'
  - 'harpy/reports/hapcut.Rmd'
  - 'harpy/bin/parse_phaseblocks.py'
simvars: &simvars
  - *common
  - *container
  - 'harpy/simulate.py'
  - 'harpy/snakefiles/simulate_snpindel.smk'
  - 'harpy/snakefiles/simulate_variants.smk'
  - 'test/vcf/test.bcf'
  - 'harpy/scripts/simuG.pl'
simreads: &simreads
  - *common
  - *container
  - 'harpy/simulate.py'
  - 'harpy/snakefiles/simulate_linkedreads.smk'
  - 'test/genome**gz'
  - 'extractReads.cpp'
  - 'harpy/bin/10xtoHaplotag.py'
  - 'harpy/scripts/LRSIM_harpy.pl'
assembly: &assembly
  - *common
  - *container
  - 'harpy/assembly.py'
  - 'harpy/metassembly.py'
  - 'harpy/snakefiles/assembly.smk'
  - 'harpy/snakefiles/metassembly.smk'
other: &other
  - 'harpy/stitchparams.py'
  - 'harpy/popgroup.py'
  - 'harpy/hpc.py'
modules:
  - *common
  - *demux
  - *deconvolve
  - *preflight
  - *qc
  - *bwa
  - *ema
  - *strobealign
  - *mpileup
  - *freebayes
  - *impute
  - *phase
  - *leviathan
  - *naibr
  - *simvars
  - *simreads
  - *assembly
  - *other
