common: &common
  - 'harpy/common/**'
  - 'harpy/__main__.py'
  - 'harpy/validation/**'
  - 'harpy/report/**'
  - '.github/workflows/tests.yml'
  - '.github/filters.yml'
environments: &environments
  - 'harpy/common/environments.py'
  - 'harpy/commands/environments.py'
  - 'harpy/environments.smk'
validate: &validate
  - *common
  - *environments
  - 'harpy/commands/validate.py'
  - 'harpy/snakefiles/validate_fastq.smk'
  - 'harpy/snakefiles/validate_bam.smk'
  - 'test/fastq/**'
  - 'test/bam/**'
  - 'harpy/scripts/check_bam.py'
  - 'harpy/scripts/check_fastq.py'
  - 'harpy/notebooks/validate_fastq.ipynb'
  - 'harpy/notebooks/validate_bam.ipynb'
deconvolve: &deconvolve
  - *common
  - *environments
  - 'harpy/commands/deconvolve.py'
  - 'harpy/snakefiles/deconvolve.smk'
preproc: &preproc
  - *common
  - *environments
  - 'harpy/commands/preprocess.py'
  - 'harpy/snakefiles/preprocess**.smk'
  - 'haplotag-acbd.py'
  - 'test/data/preproc/**'
qc: &qc
  - *common
  - *environments
  - 'harpy/commands/qc.py'
  - 'harpy/snakefiles/qc.smk'
  - 'harpy/scripts/count_bx.py'
  - 'test/fastq/**'
bwa: &bwa
  - *common
  - *environments
  - 'harpy/commands/align.py'
  - 'harpy/snakefiles/align_bwa.smk'
  - 'harpy/notebooks/align_stats.ipynb'
  - 'harpy/notebooks/align_bxstats.ipynb'
  - 'harpy/scripts/bx_stats.py'
  - 'harpy/scripts/molecule_coverage.py'
  - 'test/fastq/**'
strobealign: &strobealign
  - *common
  - *environments
  - 'harpy/commands/align.py'
  - 'harpy/snakefiles/align_strobealign.smk'
  - 'harpy/notebooks/align_stats.ipynb'
  - 'harpy/notebooks/align_bxstats.ipynb'
  - 'harpy/scripts/bx_stats.py'
  - 'harpy/scripts/molecule_coverage.py'
  - 'test/fastq/**'
mpileup: &mpileup
  - *common
  - *environments
  - 'harpy/commands/snp.py'
  - 'harpy/snakefiles/snp_mpileup.smk'
  - 'harpy/notebooks/bcftools_stats.ipynb'
  - 'test/bam/**'
freebayes: &freebayes
  - *common
  - *environments
  - 'harpy/commands/snp.py'
  - 'harpy/snakefiles/snp_freebayes.smk'
  - 'harpy/notebooks/bcftools_stats.ipynb'
  - 'test/bam/**'
impute: &impute
  - *common
  - *environments
  - 'harpy/commands/impute.py'
  - 'harpy/snakefiles/impute.smk'
  - 'test/bam/**'
  - 'test/vcf/test.bcf'
  - 'harpy/notebooks/impute.ipynb'
  - 'harpy/notebooks/stitch_collate.ipynb'
leviathan: &leviathan
  - *common
  - *environments
  - 'harpy/commands/sv.py'
  - 'harpy/snakefiles/sv_leviathan.smk'
  - 'harpy/notebooks/leviathan**.ipynb'
  - 'test/bam/**'
naibr: &naibr
  - *common
  - *environments
  - 'harpy/commands/sv.py'
  - 'harpy/snakefiles/sv_naibr.smk'
  - 'harpy/notebooks/naibr.ipynb'
  - 'harpy/scripts/infer-sv.py'
  - 'test/bam_phased/**'
phase: &phase
  - *common
  - *environments
  - 'harpy/commands/phase.py'
  - 'harpy/snakefiles/phase_snp.smk'
  - 'harpy/snakefiles/phase_bam.smk'
  - 'test/bam/**'
  - 'test/vcf/test.bcf'
  - 'harpy/notebooks/hapcut.ipynb'
  - 'harpy/scripts/parse_phaseblocks.py'
assembly: &assembly
  - *common
  - *environments
  - 'harpy/commands/assembly.py'
  - 'harpy/commands/metassembly.py'
  - 'harpy/snakefiles/assembly.smk'
  - 'harpy/snakefiles/metassembly.smk'
other: &other
  - *common
  - 'harpy/commands/template.py'
  - 'harpy/commands/hpc.py'
resume: &resume
  - 'harpy/commands/resume.py'
