common: &common
  - 'src/harpy/helperfunctions.py'
  - 'src/harpy/printfunctions.py'
  - 'src/harpy/fileparsers.py'
  - 'src/harpy/validations.py'
  - 'src/harpy/__main__.py'
  - 'resources/harpy.yaml'
  - '.github/workflows/tests.yml'
  - 'resources/buildforCI.sh'
preflight:
  - *common
  - 'src/harpy/preflight.py'
  - 'src/harpy/rules/preflight-fastq.smk'
  - 'src/harpy/rules/preflight-bam.smk'
  - 'test/fastq/**'
  - 'test/bam/**'
  - 'src/harpy/scripts/checkBAM.py'
  - 'src/harpy/scripts/checkFASTQ.py'
  - 'src/harpy/reports/PreflightFastq.Rmd'
  - 'src/harpy/reports/PreflightBam.Rmd'
demux:
  - *common
  - 'src/harpy/demultiplex.py'
  - 'src/harpy/rules/demultiplex**.smk'
  - '**demuxGen1'
  - 'bcFiles.py'
  - 'test/data/demux/**'
qc:
  - *common
  - 'src/harpy/qc.py'
  - 'src/harpy/rules/qc.smk'
  - 'test/fastq/**'
bwa:
  - *common
  - 'src/harpy/align.py'
  - 'src/harpy/rules/align-bwa.smk'
  - 'src/harpy/reports/AlignStats.Rmd'
  - 'src/harpy/reports/BxCount.Rmd'
  - 'src/harpy/scripts/bxStats.py'
  - 'src/harpy/scripts/countBX.py'
  - 'src/harpy/globalscripts/makeWindows.py'
  - 'test/fastq/**'
ema:
  - *common
  - 'src/harpy/align.py'
  - 'src/harpy/rules/align-ema.smk'
  - 'src/harpy/reports/AlignStats.Rmd'
  - 'src/harpy/reports/EmaCount.Rmd'
  - 'src/harpy/reports/BxCount.Rmd'
  - 'src/harpy/scripts/bxStats.py'
  - 'src/harpy/scripts/countBX.py'
  - 'src/harpy/globalscripts/makewindows.py'
  - 'test/fastq/**'
minimap:
  - *common
  - 'src/harpy/align.py'
  - 'src/harpy/rules/align-minimap.smk'
  - 'src/harpy/reports/AlignStats.Rmd'
  - 'src/harpy/reports/BxCount.Rmd'
  - 'src/harpy/scripts/bxStats.py'
  - 'src/harpy/scripts/countBX.py'
  - 'src/harpy/globalscripts/makewindows.py'
  - 'test/fastq/**'
mpileup:
  - *common
  - 'src/harpy/snp.py'
  - 'src/harpy/rules/snp-mpileup.smk'
  - 'src/harpy/reports/BcftoolsStats.Rmd'
  - 'src/harpy/globalscripts/makewindows.py'
  - 'test/bam/**'
freebayes:
  - *common
  - 'src/harpy/snp.py'
  - 'src/harpy/rules/snp-freebayes.smk'
  - 'src/harpy/reports/BcftoolsStats.Rmd'
  - 'src/harpy/globalscripts/makewindows.py'
  - 'test/bam/**'
impute:
  - *common
  - 'src/harpy/impute.py'
  - 'src/harpy/rules/impute.smk'
  - 'test/bam/**'
  - 'test/vcf/test.bcf'
  - 'src/harpy/reports/Impute.Rmd'
  - 'src/harpy/reports/StitchCollate.Rmd'
  - 'src/harpy/scripts/stitch_impute.R'
leviathan:
  - *common
  - 'src/harpy/sv.py'
  - 'src/harpy/rules/sv-leviathan**.smk'
  - 'test/bam/**'
  - 'src/harpy/reports/Leviathan**.Rmd'
naibr:
  - *common
  - 'src/harpy/sv.py'
  - 'src/harpy/rules/sv-naibr**.smk'
  - 'test/bam/**'
  - 'test/bam_phased/**'
  - 'test/vcf/test.phased.bcf'
  - 'src/harpy/reports/Naibr**.Rmd'
  - 'src/harpy/globalscripts/inferSV.py'
phase:
  - *common
  - 'src/harpy/phase.py'
  - 'src/harpy/rules/phase.smk'
  - 'test/bam/**'
  - 'test/vcf/test.bcf'
  - 'src/harpy/reports/HapCut2.Rmd'
  - 'src/harpy/globalscripts/parsePhaseBlocks.py'
simvars:
  - *common
  - 'src/harpy/simulatevariants.py'
  - 'simulate-snpindel.smk'
  - 'simulate-variants.smk'
  - 'test/vcf/test.bcf'
  - 'src/harpy/scripts/simuG.pl'
simreads:
  - *common
  - 'src/harpy/simulatelinkedreads.py'
  - 'simulate-linkedreads.smk'
  - 'test/genome**gz'
  - 'extractReads.cpp'
  - 'src/harpy/globalscripts/10xtoHaplotag.py'
  - 'src/harpy/scripts/LRSIMharpy.pl'
other:
  - '.github/workflows/tests.yml'
  - 'src/harpy/stitchparams.py'
  - 'src/harpy/popgroup.py'