common: &common
  - 'harpy/common/launch.py'
  - 'harpy/common/workflow.py'
  - 'harpy/common/misc.py'
  - 'harpy/common/cli_types_generic.py'
  - 'harpy/common/cli_types_params.py'
  - 'harpy/common/parsers.py'
  - 'harpy/common/printing.py'
  - 'harpy/common/validations.py'
  - 'harpy/__main__.py'
  - 'resources/harpy.yaml'
  - '.github/workflows/tests.yml'
  - '.github/filters.yml'
  - 'resources/buildforCI.sh'
environments: &environments
  - 'harpy/common/conda.py'
  - 'harpy/environments.py'
  - 'harpy/environments.smk'
validate: &validate
  - *common
  - *environments
  - 'harpy/validate.py'
  - 'harpy/snakefiles/validate_fastq.smk'
  - 'harpy/snakefiles/validate_bam.smk'
  - 'test/fastq/**'
  - 'test/bam/**'
  - 'harpy/scripts/check_bam.py'
  - 'harpy/scripts/check_fastq.py'
  - 'harpy/reports/validate_fastq.qmd'
  - 'harpy/reports/validate_bam.qmd'
deconvolve: &deconvolve
  - *common
  - *environments
  - 'harpy/deconvolve.py'
  - 'harpy/snakefiles/deconvolve.smk'
demux: &demux
  - *common
  - *environments
  - 'harpy/demultiplex.py'
  - 'harpy/snakefiles/demultiplex**.smk'
  - 'haplotag_acbd.py'
  - 'test/data/demux/**'
qc: &qc
  - *common
  - *environments
  - 'harpy/qc.py'
  - 'harpy/snakefiles/qc.smk'
  - 'test/fastq/**'
bwa: &bwa
  - *common
  - *environments
  - 'harpy/align.py'
  - 'harpy/snakefiles/align_bwa.smk'
  - 'harpy/reports/align_stats.qmd'
  - 'harpy/reports/align_bxstats.qmd'
  - 'harpy/scripts/bx_stats.py'
  - 'harpy/scripts/count_bx.py'
  - 'harpy/scripts/assign_mi.py'
  - 'harpy/scripts/molecule_coverage.py'
  - 'test/fastq/**'
ema: &ema
  - *common
  - *environments
  - 'harpy/align.py'
  - 'harpy/snakefiles/align_ema.smk'
  - 'harpy/reports/align_stats.qmd'
  - 'harpy/reports/align_bxstats.qmd'
  - 'harpy/scripts/bx_stats.py'
  - 'harpy/scripts/count_bx.py'
  - 'harpy/scripts/molecule_coverage.py'
  - 'test/fastq/**'
strobealign: &strobealign
  - *common
  - *environments
  - 'harpy/align.py'
  - 'harpy/snakefiles/align_strobealign.smk'
  - 'harpy/reports/align_stats.qmd'
  - 'harpy/reports/align_bxstats.qmd'
  - 'harpy/scripts/assign_mi.py'
  - 'harpy/scripts/bx_stats.py'
  - 'harpy/scripts/count_bx.py'
  - 'harpy/scripts/molecule_coverage.py'
  - 'test/fastq/**'
mpileup: &mpileup
  - *common
  - *environments
  - 'harpy/snp.py'
  - 'harpy/snakefiles/snp_mpileup.smk'
  - 'harpy/reports/bcftools_stats.qmd'
  - 'harpy/scripts/make_windows.py'
  - 'test/bam/**'
freebayes: &freebayes
  - *common
  - *environments
  - 'harpy/snp.py'
  - 'harpy/snakefiles/snp_freebayes.smk'
  - 'harpy/reports/bcftools_stats.qmd'
  - 'harpy/scripts/make_windows.py'
  - 'test/bam/**'
impute: &impute
  - *common
  - *environments
  - 'harpy/impute.py'
  - 'harpy/snakefiles/impute.smk'
  - 'test/bam/**'
  - 'test/vcf/test.bcf'
  - 'harpy/reports/impute.qmd'
  - 'harpy/reports/stitch_collate.qmd'
leviathan: &leviathan
  - *common
  - *environments
  - 'harpy/sv.py'
  - 'harpy/snakefiles/sv_leviathan**.smk'
  - 'test/bam/**'
  - 'harpy/scripts/concatenate_bam.py'
  - 'harpy/scripts/leviathan_bx_shim.py'
  - 'harpy/reports/leviathan**.qmd'
naibr: &naibr
  - *common
  - *environments
  - 'harpy/sv.py'
  - 'harpy/snakefiles/sv_naibr**.smk'
  - 'harpy/scripts/concatenate_bam.py'
  - 'test/bam/**'
  - 'test/bam_phased/**'
  - 'test/vcf/test.phased.bcf'
  - 'harpy/reports/naibr**.qmd'
  - 'harpy/scripts/infer_sv.py'
phase: &phase
  - *common
  - *environments
  - 'harpy/phase.py'
  - 'harpy/snakefiles/phase.smk'
  - 'test/bam/**'
  - 'test/vcf/test.bcf'
  - 'harpy/reports/hapcut.qmd'
  - 'harpy/scripts/parse_phaseblocks.py'
simvars: &simvars
  - *common
  - *environments
  - 'harpy/simulate.py'
  - 'harpy/simulate_variants.py'
  - 'harpy/snakefiles/simulate_snpindel.smk'
  - 'harpy/snakefiles/simulate_variants.smk'
  - 'test/vcf/test.bcf'
simreads: &simreads
  - *common
  - *environments
  - 'harpy/simulate.py'
  - 'harpy/simulate_linkedreads.py'
  - 'harpy/snakefiles/simulate_linkedreads.smk'
  - 'test/genome**gz'
  - 'extractReads.cpp'
  - 'harpy/scripts/haplotag_barcodes.py'
assembly: &assembly
  - *common
  - *environments
  - 'harpy/assembly.py'
  - 'harpy/metassembly.py'
  - 'harpy/snakefiles/assembly.smk'
  - 'harpy/snakefiles/metassembly.smk'
other: &other
  - *common
  - 'harpy/template.py'
  - 'harpy/hpc.py'
  - 'harpy/downsample.py'
convert: &convert
  - *common
  - 'harpy/convert.py'
modules:
  - *common
  - *demux
  - *deconvolve
  - *validate
  - *qc
  - *bwa
  - *ema
  - *strobealign
  - *mpileup
  - *freebayes
  - *impute
  - *phase
  - *leviathan
  - *naibr
  - *simvars
  - *simreads
  - *assembly
  - *other
  - *convert
