[workspace]
name = "harpy"
authors = ["pdimens <pdimens@gmail.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]
version = "3.2.0"

[tasks]

[dependencies]
bcftools = "1.22.*"
click = ">=8.2"
conda = ">=24.8"
htslib = "1.22.*"
pysam = "0.23.*"
python = ">=3.11"
rich-click = ">=1.9.3"
snakemake-minimal = ">=9.13"
samtools = "1.22.*"
seqtk = "*"
apptainer = ">=1.4.2,<2"

[pypi-dependencies]
harpy = { path = ".", editable = true}
