[workspace]
name = "harpy"
authors = ["pdimens <pdimens@gmail.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]
version = "4.0"

[tasks]

[dependencies]
bcftools = "1.22.*"
click = ">=8.2"
conda = ">=24.8"
htslib = "1.22.*"
pysam = "0.23.*"
python = ">=3.11"
rich-click = ">=1.9.3"
snakemake-minimal = ">=9.13"
samtools = "1.22.*"
seqtk = "*"
apptainer = ">=1.4.2,<2"
djinn = ">=1.1,<2"
jupyter-book = ">=2.1.0,<3"
itables = ">=2.6.2,<3"
pandas = ">=2.3.3,<3"
altair = ">=6.0.0,<7"
papermill = ">=2.6.0,<3"

[pypi-dependencies]
harpy = { path = ".", editable = true}
