[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[project]
name = "harpy"
version = "4.1.5"
authors = [{name = "Pavel Dimens"}]
description = "Automated workflows to preprocess sequences, trim reads, map sequences, call variants, impute genotypes, and phase haplotypes of Haplotagging data. Batteries included."
requires-python = ">=3.11"
readme = {file = "README.md", content-type = "text/markdown"}
license = "GPL-3.0-or-later"
dependencies = [
    'altair>=6.0.0',
    'click>8.0',
    'jupyter-book',
    'notebook',
    'papermill',
    'pandas>=3,<4',
    'pillow',
    'polars>=1.39.2',
    'pysam>=0.23',
    'rich-click>=1.8',
    'snakemake>=9.0',
    'vl-convert-python',
]

[project.scripts]
harpy = "harpy.__main__:cli"
hv = "harpy.commands.view:view"
harpy-utils = "harpy.utils:cli"

[project.urls]
Homepage = "https://github.com/pdimens/harpy"

[tool.setuptools.packages.find]
exclude = [".pixi/*", "_build/*", ".environments/*", ".vscode/*", ".report/*", "test/*", ".deprecated/*", "resources/*", ".github/*", "docs/*"]

[tool.setuptools.package-data]
harpy = ["**/*"]

# ---- pixi config -----------------------

[tool.pixi.workspace]
authors = ["pdimens <pdimens@gmail.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64"]

[tool.pixi.dependencies]
altair = ">=6.0.0,<7"
bcftools = ">=1.23"
click = ">=8.2"
conda = ">=24.8"
djinn = ">=2.4"
go = ">=1.26.1,<2"
htslib = "1.23.*"
jupyter-book = ">=2.1.0,<3"
pandas = ">=3,<4"
papermill = ">=2.6.0,<3"
polars = ">=1.39.2,<2"
pillow = ">=12.2.0,<13"
pysam = "0.23.*"
python = ">=3.11"
rich-click = ">=1.9.3"
samtools = ">=1.23"
seqtk = "*"
snakemake-minimal = ">=9.19.0,<10"
vl-convert-python = ">=2.0.0rc1,<3"
xeus-python = ">=0.18.1,<0.20"

[tool.pixi.pypi-dependencies]
harpy = { path = ".", editable = true }

[tool.pixi.activation]
env = { JUPYTER_NOTARY_DB = ":memory:" }

[tool.pixi.tasks]
build-stagger     = {cmd = "go build -C harpy/utils/stagger -o ../gih-stagger -ldflags='-s -w' stagger.go", inputs = ["harpy/utils/stagger/stagger.go"], outputs = ["harpy/utils/gih-stagger"]}
build-convert     = {cmd = "go build -C harpy/utils/convert -o ../gih-convert -ldflags='-s -w' convert.go", inputs = ["harpy/utils/convert/convert.go"], outputs = ["harpy/utils/gih-convert"]}
build-standardize = {cmd = "go build -C harpy/utils/standardize -o ../djinn-standardize -ldflags='-s -w' standardize.go", inputs = ["harpy/utils/standardize/standardize.go"], outputs = ["harpy/utils/djinn-standardize"]}
install = {cmd = "chmod +x harpy/utils/gih-stagger harpy/utils/gih-convert harpy/utils/djinn-standardize && mv harpy/utils/gih-stagger harpy/utils/gih-convert harpy/utils/djinn-standardize $CONDA_PREFIX/bin/", depends-on = ["build-stagger", "build-convert", "build-standardize"]}
build = {depends-on = ["install"]}
