#! /usr/bin/env bash

in1=$1
in2=$2

if [[ -z $1 ]]; then
    echo "Interleave two FASTQ files, putting the BX:Z: tag at the end of the read name. Results are piped to stdout."
    echo "Two input FASTQ files are required, the first being R1, the second R2."
    echo -e "\n [usage]: emaInterleave file1.R1.fq.gz file2.R2.fq.gz | bgzip > outfile.R1R2.fq.gz"
    exit 1
fi

if [[ -z $2 ]]; then
    echo "ERROR:"
    echo "Two input FASTQ files are required, the first being R1, the second R2."
    exit 1
fi

FASTQpaste () {
    # add BX tag with a space to keep formatting from getting messed up
    gzip -c -d $1 | paste - - - - | awk '{print $1" "$2"\t"$5"\t"$6"\t"$7}'
}

# last tr command converts the \sBX: tag to \tBX:
paste <(FASTQpaste $in1) <(FASTQpaste $in2) | tr "\t" "\n" | tr "\s" "\t"

