{{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv

## shell completion scripts (bash, zsh, fish), written to share/harpy/ and sourced on activation
mkdir -p ${PREFIX}/share/harpy
for _shell in bash zsh fish; do
    {{ PYTHON }} -m harpy completion ${_shell} > ${PREFIX}/share/harpy/complete.${_shell}
done

## build Go binaries
{
    cd harpy/utils
    go build -C stagger -o ../gih-stagger -ldflags='-s -w' stagger.go
    go build -C convert -o ../gih-convert -ldflags='-s -w' convert.go
    go build -C standardize -o ../djinn-standardize -ldflags='-s -w' standardize.go 
    chmod +x gih-stagger gih-convert djinn-standardize
    mv gih-stagger gih-convert djinn-standardize ${PREFIX}/bin/
}

## activate/deactive processes
mkdir -p $PREFIX/etc/conda/activate.d
mkdir -p $PREFIX/etc/conda/deactivate.d

## Keep these two hooks identical to resources/shell_completion.{sh,fish} (checked by test/cli/check_lazy_cli.py)
cat > ${PREFIX}/etc/conda/activate.d/harpy-completion.sh <<'EOF_COMPLETION_SH'
# Sourced on activation of the harpy environment (conda activate.d / pixi activation script).
# Enables tab-completion for harpy in bash and zsh using the scripts that are written to
# $CONDA_PREFIX/share/harpy/ when harpy is built (generated by `harpy completion`).
# Only does anything in interactive shells, and silently skips if the scripts are missing.
case $- in
  *i*)
    _harpy_completion_dir="${CONDA_PREFIX-}/share/harpy"
    if [ -n "${BASH_VERSION-}" ] && [ -f "${_harpy_completion_dir}/complete.bash" ]; then
      . "${_harpy_completion_dir}/complete.bash"
    elif [ -n "${ZSH_VERSION-}" ] && [ -f "${_harpy_completion_dir}/complete.zsh" ] && type compdef >/dev/null 2>&1; then
      # compdef only exists if the user has initialized zsh completion (compinit)
      . "${_harpy_completion_dir}/complete.zsh"
    fi
    unset _harpy_completion_dir
    ;;
esac
EOF_COMPLETION_SH

cat > ${PREFIX}/etc/conda/activate.d/harpy-completion.fish <<'EOF_COMPLETION_FISH'
# Sourced on activation of the harpy environment (conda activate.d).
# Enables tab-completion for harpy in fish using the script that is written to
# $CONDA_PREFIX/share/harpy/ when harpy is built (generated by `harpy completion`).
if status is-interactive; and test -f "$CONDA_PREFIX/share/harpy/complete.fish"
    source "$CONDA_PREFIX/share/harpy/complete.fish"
end
EOF_COMPLETION_FISH

cat > ${PREFIX}/etc/conda/activate.d/harpy-activate.sh <<'EOF'  
export _HARPY_OLD_JUPYTER_NOTARY_DB="${JUPYTER_NOTARY_DB-__UNSET__}"  
export JUPYTER_NOTARY_DB=':memory:'

python -m ipykernel install --prefix "$CONDA_PREFIX" --name ipython-harpy \
    --display-name "Python (harpy)"
EOF
  
cat > ${PREFIX}/etc/conda/deactivate.d/harpy-deactivate.sh <<'EOF'  
if [ "${_HARPY_OLD_JUPYTER_NOTARY_DB-__UNSET__}" = "__UNSET__" ]; then  
  unset JUPYTER_NOTARY_DB  
else  
  export JUPYTER_NOTARY_DB="${_HARPY_OLD_JUPYTER_NOTARY_DB}"  
fi  
unset _HARPY_OLD_JUPYTER_NOTARY_DB  
EOF
