name: "There's an issue"
description: Something about harpy is not working or behaving in the way you expect
labels: bug
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the issue
      description: A clear and concise description of what's going wrong. Please do note paste in the contents of example files (do that below), but it may be helpful in some cases to see your project directory structure. 
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Harpy Version
      description: If not the latest version, which version are you using?
      placeholder: use `harpy --version` to find the version number

  - type: textarea
    id: error-file
    attributes:
      label: File triggering the error (if applicable)
      description: Please drag and drop (and upload to the GitHub issue) an input file that can be used to replicate the error. You may also copy-and-paste it as a code block. If the file type is not allowed, please compress into a `.zip` or `.gz` file. Alternatively, a snakemake log file would be helpful here too.
      placeholder: |
        [ Copy and paste or drag and drop an example file here to upload ]

  - type: textarea
    id: log
    attributes:
      label: Harpy error log
      description: Please paste your **full harpy command** and whatever error messages you are seeing that are specific to your workflow and not a generic harpy error message. Helpful information will include which snakemake rules are creating problems, if any.
      render: console
      placeholder: |
        $ harpy preflight bam test/bam test/bam_phased
        ╭─ Error ─────────────────────────────────────────────────────────────────╮
        │ Identical filenames were detected, which will cause unexpected behavior │
        │ and results. Note that files with identical names but different-cased   │
        │ extensions are treated as identical.                                    │
        ╰─────────────────────────────────────────────────────────────────────────╯
        ╭─ Solution ──────────────────────────────────────────────────────────────╮
        │ Make sure all input files have unique names.                            │
        ╰────────────────────── Files with clashing names: ───────────────────────╯
        test/bam/sample2.bam test/bam_phased/sample2.bam
        test/bam/sample1.bam test/bam_phased/sample1.bam

