name: Question
description: Questions about running Harpy unrelated to issues
labels: question
body:
  - type: textarea
    id: description
    attributes:
      label: Question
      description: Please describe your question with as much relevant context as possible.
    validations:
      required: true
