__use_yte__: true
executor: slurm
default-resources:
	slurm_account: $USER
	slurm_partition: regular
	mem_mb: attempt * 2000
jobs: 50
latency-wait: 60
retries: 1

# This section is for advanced copying into a scratch directory #
#default-storage-provider: fs
#local-storage-prefix: /home2/$USER
#shared-fs-usage:
#- persistence
#- software-deployment
#- sources
#- source-cache
