cores: 4
rerun-incomplete: true
show-failed-logs: true
rerun-triggers:
- mtime
- params
quiet: reason
scheduler: greedy
nolock: true
software-deployment-method: conda
conda-prefix: /home/pdimens/Documents/harpy/.environments
conda-cleanup-pkgs: cache
apptainer-prefix: /home/pdimens/Documents/harpy/.environments
directory: /home/pdimens/Documents/harpy/Preprocess
