Workflow:
  name: preprocess_gih
  reports:
    skip: false
  snakemake:
    absolute: snakemake --snakefile /home/pdimens/Documents/harpy/Preprocess/workflow/workflow.smk --configfile /home/pdimens/Documents/harpy/Preprocess/workflow/workflow.yaml --profile /home/pdimens/Documents/harpy/Preprocess/workflow --notemp
    relative: snakemake --snakefile Preprocess/workflow/workflow.smk --configfile Preprocess/workflow/workflow.yaml --profile Preprocess/workflow --notemp
    conda-envs:
    - qc
Parameters:
  ME-sequence: AGATGTGTATAAGAGACAG
  ME-overlap: 19
  minimum-length: 50
Inputs:
- /home/pdimens/Documents/harpy/test/preproc/gih_001.R1.fq.gz
