brand:
  logo: 
    medium: https://raw.githubusercontent.com/pdimens/harpy/docs/static/logo_navbar.png
execute:
    echo: false
    warning: false
embed-resources: true
format: 
  dashboard:
    theme: materia
    scrolling: true
    expandable: false
    logo: https://raw.githubusercontent.com/pdimens/harpy/docs/static/logo_navbar.png
    nav-buttons:
      - icon: book-half
        href: https://pdimens.github.io/harpy
      - icon: bug
        href: https://github.com/pdimens/harpy/issues/new/choose
      - icon: code-slash
        href: https://github.com/pdimens/harpy