brand:
  logo:
    medium: https://raw.githubusercontent.com/pdimens/harpy/docs/static/favicon_report.svg
execute:
    echo: false
    warning: false
embed-resources: true
format:
  dashboard:
    theme: 
      - lumen
      - harpy.scss
    scrolling: true
    expandable: false
    logo: https://raw.githubusercontent.com/pdimens/harpy/docs/static/favicon_report.svg
    nav-buttons:
      - icon: book-half
        href: https://pdimens.github.io/harpy
      - icon: bug
        href: https://github.com/pdimens/harpy/issues/new/choose
      - icon: code-slash
        href: https://github.com/pdimens/harpy
    include-in-header:
      text: |
        <link rel="shortcut icon" href="https://raw.githubusercontent.com/pdimens/harpy/docs/static/favicon_report.svg" />
        <link rel="icon" type="image/x-icon" href="https://raw.githubusercontent.com/pdimens/harpy/docs/static/favicon_report.svg">