name: Test Align

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'workflow/envs/harpy.yaml'
      - 'workflow/envs/r-env.yaml'
      - 'workflow/envs/align.yaml'
      - 'workflow/rules/align-**.smk'
      - '**align.py'
      - '**helperfunctions.py'
      - 'reports/reportBwaGencov.Rmd'
      - 'reports/reportEmaGencov.Rmd'
      - 'reports/reportEmaCount.Rmd'
      - 'reports/reportBxCount.Rmd'
      - 'reports/reportBxStats.Rmd'
      - 'utilities/bxStats.py'
      - 'utilities/countBX.py'
      - 'utilities/makewindows.py'
      - 'test/fastq/**'
      - '**align.yml'
      - '**__main__.py'

  pull_request:
    branches:
      - 'dev'
    paths:
      - 'workflow/envs/harpy.yaml'
      - 'workflow/envs/r-env.yaml'
      - 'workflow/envs/align.yaml'
      - 'workflow/rules/align-**.smk'
      - '**align.py'
      - '**helperfunctions.py'
      - 'reports/reportBwaGencov.Rmd'
      - 'reports/reportEmaGencov.Rmd'
      - 'reports/reportEmaCount.Rmd'
      - 'reports/reportBxCount.Rmd'
      - 'reports/reportBxStats.Rmd'
      - 'utilities/bxStats.py'
      - 'utilities/countBX.py'
      - 'utilities/makewindows.py'
      - 'test/fastq/**'
      - '**align.yml'
      - '**__main__.py'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  test_bwa:
    name: bwa
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: setup mamba
        uses: mamba-org/setup-micromamba@v1
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: workflow/envs/harpy.yaml
          cache-environment: true
          post-cleanup: 'all'
          log-level: error
      - name: Install harpy
        run: |
          python3 -m pip install --upgrade build && python3 -m build
          pip install dist/*.whl
          resources/buildforCI.sh
        shell: micromamba-shell {0}
      - name: test bwa
        shell: micromamba-shell {0}
        run: harpy align bwa -d test/fastq -g test/genome/genome.fasta.gz -s "--show-failed-logs"
        continue-on-error: true

      - name: align ema
        if: always()
        shell: micromamba-shell {0}
        run: harpy align ema --ema-bins 20 -d test/fastq -g test/genome/genome.fasta.gz -s "--show-failed-logs"