name: Test Align

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev'

# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  changes:
  runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      bwa: ${{ steps.filter.outputs.bwa }}
      ema: ${{ steps.filter.outputs.ema }}
      minimap: ${{ steps.filter.outputs.minimap }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            bwa:
              - 'resources/harpy.yaml'
              - 'src/harpy/rules/align-bwa.smk'
              - '**align.py'
              - '**helperfunctions.py'
              - '**printfunctions.py'
              - '**fileparsers.py'
              - '**validations.py'
              - 'src/harpy/reports/Gencov.Rmd'
              - 'src/harpy/reports/BxCount.Rmd'
              - 'src/harpy/reports/BxStats.Rmd'
              - 'src/harpy/scripts/bxStats.py'
              - 'src/harpy/scripts/countBX.py'
              - 'globalscripts/makewindows.py'
              - 'test/fastq/**'
              - '**align.yml'
              - '**__main__.py'
            ema:
              - 'resources/harpy.yaml'
              - 'src/harpy/rules/align-ema.smk'
              - '**align.py'
              - '**helperfunctions.py'
              - '**printfunctions.py'
              - '**fileparsers.py'
              - '**validations.py'
              - 'src/harpy/reports/EmaGencov.Rmd'
              - 'src/harpy/reports/EmaCount.Rmd'
              - 'src/harpy/reports/BxCount.Rmd'
              - 'src/harpy/reports/BxStats.Rmd'
              - 'src/harpy/scripts/bxStats.py'
              - 'src/harpy/scripts/countBX.py'
              - 'globalscripts/makewindows.py'
              - 'test/fastq/**'
              - '**align.yml'
              - '**__main__.py'
            minimap:
              - 'resources/harpy.yaml'
              - 'src/harpy/rules/align-minimap.smk'
              - '**align.py'
              - '**helperfunctions.py'
              - '**printfunctions.py'
              - '**fileparsers.py'
              - '**validations.py'
              - 'src/harpy/reports/Gencov.Rmd'
              - 'src/harpy/reports/BxCount.Rmd'
              - 'src/harpy/reports/BxStats.Rmd'
              - 'src/harpy/scripts/bxStats.py'
              - 'src/harpy/scripts/countBX.py'
              - 'globalscripts/makewindows.py'
              - 'test/fastq/**'
              - '**align.yml'
              - '**__main__.py'
  test_bwa:
    needs: changes
    if: ${{ needs.changes.outputs.bwa == 'true' }}
    name: test BWA
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: setup mamba
        uses: mamba-org/setup-micromamba@v1
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: resources/harpy.yaml
          cache-environment: true
          post-cleanup: 'all'
          log-level: error
      - name: Install harpy
        run: |
          python3 -m pip install --upgrade build && python3 -m build
          pip install dist/*.whl
          resources/buildforCI.sh
        shell: micromamba-shell {0}
      - name: test bwa
        shell: micromamba-shell {0}
        run: harpy align bwa -g test/genome/genome.fasta.gz -s "--show-failed-logs" -x "-A 2" test/fastq
  
  test_ema:
    needs: changes
    if: ${{ needs.changes.outputs.ema == 'true' }}
    name: test EMA
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: setup mamba
        uses: mamba-org/setup-micromamba@v1
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: resources/harpy.yaml
          cache-environment: true
          post-cleanup: 'all'
          log-level: error
      - name: Install harpy
        run: |
          python3 -m pip install --upgrade build && python3 -m build
          pip install dist/*.whl
          resources/buildforCI.sh
        shell: micromamba-shell {0}
      - name: test ema
        shell: micromamba-shell {0}
        run: harpy align ema --ema-bins 20 -g test/genome/genome.fasta.gz -s "--show-failed-logs" -x "-d" test/fastq

  test_minimap:
    needs: changes
    if: ${{ needs.changes.outputs.minimap == 'true' }}
    name: test minimap
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: setup mamba
        uses: mamba-org/setup-micromamba@v1
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: resources/harpy.yaml
          cache-environment: true
          post-cleanup: 'all'
          log-level: error
      - name: Install harpy
        run: |
          python3 -m pip install --upgrade build && python3 -m build
          pip install dist/*.whl
          resources/buildforCI.sh
        shell: micromamba-shell {0}
      - name: test minimap
        shell: micromamba-shell {0}
        run: harpy align minimap -g test/genome/genome.fasta.gz -s "--show-failed-logs" -x "--seed 13" test/fastq