name: Test Impute

on:
  push:
    branches:
      - 'dev'
    paths:
      - '**impute.smk'
      - 'workflow/envs/harpy.yaml'
      - 'workflow/envs/r-env.yaml'
      - '**impute.py'
      - '**helperfunctions.py'
      - '**printfunctions.py'
      - '**fileparsers.py'
      - '**validations.py'
      - 'test/bam/**'
      - 'test/vcf/test.bcf'
      - '**impute.yml'
      - 'workflow/report/Impute.Rmd'
      - 'workflow/report/StitchCollate.Rmd'
      - 'workflow/scripts/stitch_impute.R'
      - '**__main__.py'

  pull_request:
    branches:
      - 'dev'
    paths:
      - '**impute.smk'
      - 'workflow/envs/harpy.yaml'
      - 'workflow/envs/r-env.yaml'
      - '**impute.py'
      - '**helperfunctions.py'
      - '**printfunctions.py'
      - '**fileparsers.py'
      - '**validations.py'
      - 'test/bam/**'
      - 'test/vcf/test.bcf'
      - '**impute.yml'
      - 'reports/reportImpute.Rmd'
      - 'reports/reportStitch.Rmd'
      - 'utilities/stitch_impute.R'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:
    name: testImpute
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: setup mamba
        uses: mamba-org/setup-micromamba@v1
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: workflow/envs/harpy.yaml
          cache-environment: true
          post-cleanup: 'all'
          log-level: error
      - name: Install harpy
        shell: micromamba-shell {0}
        run: |
          python3 -m pip install --upgrade build && python3 -m build
          pip install dist/*.whl
          resources/buildforCI.sh

      - name: impute
        shell: micromamba-shell {0}
        run: harpy impute --vcf test/vcf/test.bcf -p test/stitch.params -s "--show-failed-logs" test/bam

      - name: impute from vcf
        shell: micromamba-shell {0}
        if: always()
        run: |
          rm -rf Impute
          harpy impute --vcf-samples --vcf test/vcf/test.bcf -p test/stitch.params -s "--show-failed-logs" test/bam
