name: Test Phase

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'resources/harpy.yaml'
      - 'src/harpy/rules/phase-pop.smk'
      - '**phase.py'
      - '**helperfunctions.py'
      - '**printfunctions.py'
      - '**fileparsers.py'
      - '**validations.py'
      - 'test/bam/**'
      - 'test/vcf/test.bcf'
      - '**phase.yml'
      - 'src/harpy/reports/HapCut2.Rmd'
      - 'globalscripts/parsePhaseBlocks.py'
      - '**__main__.py'

  pull_request:
    branches:
      - 'dev'

# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CACHE_NUMBER: 0  # increase to reset cache manually


jobs:
  build:
    name: testPhase
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: setup mamba
        uses: mamba-org/setup-micromamba@v1
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: resources/harpy.yaml
          cache-environment: true
          post-cleanup: 'all'
          log-level: error
      - name: Install harpy
        run: |
          python3 -m pip install --upgrade build && python3 -m build
          pip install dist/*.whl
          resources/buildforCI.sh
        shell: micromamba-shell {0}

      - name: phase
        shell: micromamba-shell {0}
        run: harpy phase --vcf test/vcf/test.bcf -s "--show-failed-logs" -x "--max_iter 10001" test/bam

      - name: phase with indels
        shell: micromamba-shell {0}
        if: always()
        run: |
          harpy phase --vcf test/vcf/test.bcf -o phaseindel -g test/genome/genome.fasta.gz -s "--show-failed-logs" test/bam

      - name: phase from vcf
        shell: micromamba-shell {0}
        if: always()
        run: |
          harpy phase --vcf-samples -o phasevcf --vcf test/vcf/test.bcf -s "--show-failed-logs" test/bam