name: Test Preflight

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'resources/harpy.yaml'
      - 'src/harpy/rules/preflight-fastq.smk'
      - 'src/harpy/rules/preflight-bam.smk'
      - '**preflight.py'
      - '**helperfunctions.py'
      - '**printfunctions.py'
      - '**fileparsers.py'
      - '**validations.py'
      - 'test/fastq/**'
      - 'test/bam/**'
      - 'src/harpy/scripts/checkBAM.py'
      - 'src/harpy/scripts/checkFASTQ.py'
      - 'src/harpy/reports/PreflightFastq.Rmd'
      - 'src/harpy/reports/PreflightBam.Rmd'
      - '**preflight.yml'
      - '**__main__.py'

  pull_request:
    branches:
      - 'dev'
    paths:
      - 'resources/harpy.yaml'
      - 'src/harpy/rules/preflight-fastq.smk'
      - 'src/harpy/rules/preflight-bam.smk'
      - '**preflight.py'
      - '**helperfunctions.py'
      - '**printfunctions.py'
      - '**fileparsers.py'
      - '**validations.py'
      - 'test/fastq/**'
      - 'test/bam/**'
      - 'src/harpy/scripts/checkBAM.py'
      - 'src/harpy/scripts/checkFASTQ.py'
      - 'src/harpy/reports/PreflightFastq.Rmd'
      - 'src/harpy/reports/PreflightBam.Rmd'
      - '**preflight.yml'
      - '**__main__.py'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  preflight_fastq:
    name: fastq
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: setup mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: resources/harpy.yaml
          cache-environment: true
          post-cleanup: 'all'
      - name: Install harpy
        shell: micromamba-shell {0}
        run: |
          python3 -m pip install --upgrade build && python3 -m build
          pip install dist/*.whl
          resources/buildforCI.sh
      - name: harpy preflight fastq
        shell: micromamba-shell {0}
        run: harpy preflight fastq test/fastq
  preflight_bam:
    name: bam
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: setup mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: resources/harpy.yaml
          cache-environment: true
          post-cleanup: 'all'
      - name: Install harpy
        shell: micromamba-shell {0}
        run: |
          python3 -m pip install --upgrade build && python3 -m build
          pip install dist/*.whl
          resources/buildforCI.sh
      - name: harpy preflight bam
        shell: micromamba-shell {0}
        run: harpy preflight bam test/bam