name: Test Preflight

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'rules/preflight-fastq.smk'
      - 'rules/preflight-bam.smk'
      - '**preflight.py'
      - '**helperfunctions.py'
      - '**printfunctions.py'
      - '**fileparsers.py'
      - '**validations.py'
      - 'test/fastq/**'
      - 'test/bam/**'
      - 'utilities/checkBAM.py'
      - 'utilities/checkFASTQ.py'
      - 'reports/reportPreflightFastq.Rmd'
      - 'reports/reportPreflightBam.Rmd'
      - '**preflight.yml'
      - '**__main__.py'

  pull_request:
    branches:
      - 'dev'
    paths:
      - 'rules/preflight-fastq.smk'
      - 'rules/preflight-bam.smk'
      - '**preflight.py'
      - '**helperfunctions.py'
      - '**printfunctions.py'
      - '**fileparsers.py'
      - '**validations.py'
      - 'test/fastq/**'
      - 'test/bam/**'
      - 'utilities/checkBAM.py'
      - 'utilities/checkFASTQ.py'
      - 'reports/reportPreflightFastq.Rmd'
      - 'reports/reportPreflightBam.Rmd'
      - '**preflight.yml'
      - '**__main__.py'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  preflight_fastq:
    name: fastq
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: setup mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: misc/harpyenv.yaml
          cache-environment: true
          post-cleanup: 'all'
      - name: Install harpy
        run: |
          python3 -m pip install --upgrade build && python3 -m build
          pip install dist/*.whl
          misc/buildforCI.sh
        shell: micromamba-shell {0}

      - name: harpy preflight fastq
        run: harpy preflight fastq -d test/fastq
        shell: micromamba-shell {0}

      - name: harpy preflight bam
        run: harpy preflight bam -d test/bam
        shell: micromamba-shell {0}