name: Test QC

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'rules/qc.smk'
      - '**qc.py'
      - '**helperfunctions.py'
      - '**printfunctions.py'
      - '**fileparsers.py'
      - '**validations.py'
      - 'test/fastq/**'
      - '**qc.yml'
      - '**__main__.py'

  pull_request:
    branches:
      - 'dev'
    paths:
      - 'rules/qc.smk'
      - '**qc.py'
      - '**helperfunctions.py'
      - '**printfunctions.py'
      - '**fileparsers.py'
      - '**validations.py'
      - 'test/fastq/**'
      - '**qc.yml'
      - '**__main__.py'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:
    name: testQC
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: setup mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: workflow/envs/harpy.yaml
          cache-environment: true
          post-cleanup: 'all'
      - name: Install harpy
        shell: micromamba-shell {0}
        run: |
          python3 -m pip install --upgrade build && python3 -m build
          pip install dist/*.whl
          resources/buildforCI.sh

      - name: harpy qc
        run: harpy qc -d test/fastq
        shell: micromamba-shell {0}