name: Rebuild Software Container

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - dev

# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  changes:
    name: detect file changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: check which files changed
        uses: dorny/paths-filter@v3
        id: changes
        with:
          base: 'dev'
          filters: |
            src:
              - 'src/harpy/conda_deps.py'
              - 'src/harpy/containerize.smk'
    outputs:
      src: ${{ steps.changes.outputs.src }}

  pkgbuild:
    needs: changes
    if: needs.changes.outputs.src == 'true'
    name: build container
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: setup mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: resources/harpy.yaml
          cache-environment: true
          post-cleanup: 'all'
      - name: Install harpy
        shell: micromamba-shell {0}
        run: |
          python3 -m pip install --upgrade build && python3 -m build
          pip install dist/*.whl
          resources/buildforCI.sh
      - name: Clear space
        run: rm -rf /opt/hostedtoolcache
      - name: Rebuild dockerfile
        shell: micromamba-shell {0}
        run: harpy containerize
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: pdimens/harpy:latest
