
name: Publish Docs with Retype
on:
  workflow_dispatch:
  push:
    branches:
      - docs

jobs:
  publish:
    name: Publish to retype branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: docs
      - uses: retypeapp/action-build@latest
      - uses: retypeapp/action-github-pages@latest
        with:
          branch: website
          update-branch: true