name: Publish Docs with Retype
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"

jobs:
  publish:
    name: Publish to retype branch
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 1
      - uses: retypeapp/action-build@latest
        with:
          key: ${{ secrets.RETYPE_KEY }}
      - uses: retypeapp/action-github-pages@latest
        with:
          branch: website
          update-branch: true
