name: Test Simulate LinkedReads

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'simulate-linkedreads.smk'
      - 'resources/harpy.yaml'
      - '**helperfunctions.py'
      - '**printfunctions.py'
      - '**fileparsers.py'
      - 'test/genome**gz'
      - 'extractReads.cpp'
      - '10xtoHaplotag.py'
      - 'src/harpy/scripts/LRSIMharpy.pl'
      - '**__main__.py'

  pull_request:
    branches:
      - 'dev'
    paths:
      - 'simulate-linkedreads.smk'
      - 'resources/harpy.yaml'
      - '**helperfunctions.py'
      - '**printfunctions.py'
      - '**fileparsers.py'
      - 'test/genome**gz'
      - 'extractReads.cpp'
      - '10xtoHaplotag.py'
      - 'src/harpy/scripts/LRSIMharpy.pl'
      - '**__main__.py'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:
    name: test simulations
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: setup mamba
        uses: mamba-org/setup-micromamba@v1
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: resources/harpy.yaml
          cache-environment: true
          post-cleanup: 'all'
          log-level: error
      - name: Install harpy
        shell: micromamba-shell {0}
        run: |
          python3 -m pip install --upgrade build && python3 -m build
          pip install dist/*.whl
          resources/buildforCI.sh

      - name: simulate random snps/indels
        shell: micromamba-shell {0}
        run: harpy simulate linkedreads -s "--show-failed-logs" -t 4 -n 2  -l 100 -p 50 test/genome/genome.fasta.gz test/genome/genome2.fasta.gz
